## DATASET
importing the neccessary libraries and
reading the dataset to a pandas dataframe 

In [32]:
import pandas as pd
import numpy as np
data=pd.read_csv(r'C:\Users\ANONYMOUS\Documents\rc\rc.txt')
print(data)

    amount                 serial                pin  network   pin1   pin2  \
0      100        680808605904017    881400534676230      glo  88140   5346   
1      100        780701004928996    118373330935056      glo  11837  33309   
2      100        780701004928999    118373186445630      glo  11837  31864   
3      100        780701005054210    118386398414930      glo  11838  63984   
4      100        780701303616893    150921276010823      glo  15092  12760   
5      100        780701005002489    118381320325769      glo  11838  13203   
6      100        780701005323925    118412934638017      glo  11841  29346   
7      100        780701004634033    118344180476326      glo  11834  41804   
8      200        490609014659535    907892806242643      glo  90789  28062   
9      100              883397510         1506166242      mtn  15061  66242   
10     100             7071826979  56587275767647829      mtn   5658   7275   
11     100             7059560842  54991327602979462

In [33]:
X=rc[['pin1', 'pin2', 'pin3', 'pin4']]
Y=rc['network']

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X,Y, test_size=0.3)

## Implementing Decision Tree

In [39]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()

In [41]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [51]:
dtc_pred=dtc.predict(x_test)
print(y_test.values, '\n', dtc_pred)
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test.values, dtc_pred))
print('accuracy= ',accuracy_score(y_test.values, dtc_pred)*100)

['airtel' 'glo' 'mtn' 'glo' 'airtel' 'glo'] 
 ['airtel' 'glo' 'airtel' 'mtn' 'airtel' 'glo']
[[2 0 0]
 [0 2 1]
 [1 0 0]]
accuracy=  66.66666666666666


## Implementing K Nearest Neighbor
using a nearest neighbor of 1

In [53]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)
knn_pred=knn.predict(x_test)
print(y_test.values, '\n', knn_pred)
print(confusion_matrix(y_test.values, knn_pred))
print('accuracy= ',accuracy_score(y_test.values, knn_pred)*100)

['airtel' 'glo' 'mtn' 'glo' 'airtel' 'glo'] 
 ['airtel' 'glo' 'mtn' 'glo' 'airtel' 'glo']
[[2 0 0]
 [0 3 0]
 [0 0 1]]
accuracy=  100.0


## Implementing Random Forest Classifier

In [54]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc_pred=rfc.predict(x_test)
print(y_test.values, '\n', rfc_pred)
print(confusion_matrix(y_test.values, rfc_pred))
print('accuracy= ',accuracy_score(y_test.values, rfc_pred)*100)

['airtel' 'glo' 'mtn' 'glo' 'airtel' 'glo'] 
 ['airtel' 'glo' 'airtel' 'glo' 'airtel' 'glo']
[[2 0 0]
 [0 3 0]
 [1 0 0]]
accuracy=  83.33333333333334
